---

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  tags:
    - manala_postgresql
    - manala_postgresql.requirements

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_postgresql
    - manala_postgresql.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_postgresql
    - manala_postgresql.config

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_postgresql
    - manala_postgresql.services
    - manala.services

- name: Roles
  ansible.builtin.import_tasks: roles.yml
  tags:
    - manala_postgresql
    - manala_postgresql.roles

- name: Databases
  ansible.builtin.import_tasks: databases.yml
  tags:
    - manala_postgresql
    - manala_postgresql.databases

- name: Privileges
  ansible.builtin.import_tasks: privileges.yml
  tags:
    - manala_postgresql
    - manala_postgresql.privileges
