---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
     - manala_ntp
     - manala_ntp.install

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
     - manala_ntp
     - manala_ntp.services
     - manala.services
