---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_shorewall
    - manala_shorewall.install

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_shorewall
    - manala_shorewall.configs

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_shorewall
    - manala_shorewall.config
