---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_redis
    - manala_redis.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_redis
    - manala_redis.config

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_redis
    - manala_redis.services
    - manala.services
