---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_nginx
    - manala_nginx.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_nginx
    - manala_nginx.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_nginx
    - manala_nginx.configs

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_nginx
    - manala_nginx.services
    - manala.services
