---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_aptly
    - manala_aptly.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_aptly
    - manala_aptly.config

- name: Repositories
  ansible.builtin.import_tasks: repositories.yml
  tags:
    - manala_aptly
    - manala_aptly.repositories
