---

- name: Setup
  ansible.builtin.import_tasks: setup.yml
  tags:
    - manala_deploy
    - manala_deploy.setup

- name: Strategy
  ansible.builtin.import_tasks: strategy.yml
  tags:
    - manala_deploy
    - manala_deploy.strategy

- name: Unfinished
  ansible.builtin.import_tasks: unfinished.yml
  tags:
    - manala_deploy
    - manala_deploy.unfinished

- name: Shared
  ansible.builtin.import_tasks: shared.yml
  tags:
    - manala_deploy
    - manala_deploy.shared

- name: Copied
  ansible.builtin.import_tasks: copied.yml
  tags:
    - manala_deploy
    - manala_deploy.copied

- name: Writable - Dirs
  ansible.builtin.import_tasks: writable/dirs.yml
  tags:
    - manala_deploy
    - manala_deploy.dirs

- name: Tasks
  ansible.builtin.import_tasks: tasks.yml
  vars:
    __manala_deploy_tasks: "{{ manala_deploy_tasks }}"
  tags:
    - manala_deploy
    - manala_deploy.tasks

- name: Removed
  ansible.builtin.import_tasks: removed.yml
  tags:
    - manala_deploy
    - manala_deploy.removed

- name: Finalize
  ansible.builtin.import_tasks: finalize.yml
  tags:
    - manala_deploy
    - manala_deploy.finalize

- name: Clean
  ansible.builtin.import_tasks: clean.yml
  tags:
    - manala_deploy
    - manala_deploy.clean

- name: Post tasks
  ansible.builtin.import_tasks: tasks.yml
  vars:
    __manala_deploy_tasks: "{{ manala_deploy_post_tasks }}"
  tags:
    - manala_deploy
    - manala_deploy.tasks
