---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_haproxy
    - manala_haproxy.install

- name: Errorfiles
  ansible.builtin.import_tasks: errorfiles.yml
  tags:
    - manala_haproxy
    - manala_haproxy.errorfiles

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_haproxy
    - manala_haproxy.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_haproxy
    - manala_haproxy.configs

- name: Environment
  ansible.builtin.import_tasks: environment.yml
  tags:
    - manala_haproxy
    - manala_haproxy.environment

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_haproxy
    - manala_haproxy.services
    - manala.services
