---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_influxdb
    - manala_influxdb.install

- name: Dir
  ansible.builtin.import_tasks: dir.yml
  tags:
    - manala_influxdb
    - manala_influxdb.dir

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_influxdb
    - manala_influxdb.config

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_influxdb
    - manala_influxdb.services
    - manala.services

- name: Databases
  ansible.builtin.import_tasks: databases.yml
  tags:
    - manala_influxdb
    - manala_influxdb.databases

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - manala_influxdb
    - manala_influxdb.users

- name: Privileges
  ansible.builtin.import_tasks: privileges.yml
  tags:
    - manala_influxdb
    - manala_influxdb.privileges
