---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_mongodb
    - manala_mongodb.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_mongodb
    - manala_mongodb.config

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - manala_mongodb
    - manala_mongodb.users

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_mongodb
    - manala_mongodb.services
    - manala.services
