---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.configs

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.services
    - manala.services
