---

- name: Reconfigure gitlab
  ansible.builtin.command: gitlab-ctl reconfigure
  # Deprecated
  listen: gitlab reconfigure

- name: Restart gitlab
  ansible.builtin.command: gitlab-ctl restart
  # Deprecated
  listen: gitlab restart
