---

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_apt
    - manala_apt.configs

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_apt
    - manala_apt.install

- name: Sources list
  ansible.builtin.import_tasks: sources_list.yml
  tags:
    - manala_apt
    - manala_apt.sources_list

- name: Preferences
  ansible.builtin.import_tasks: preferences.yml
  tags:
    - manala_apt
    - manala_apt.preferences

- name: Keys
  ansible.builtin.import_tasks: keys.yml
  tags:
    - manala_apt
    - manala_apt.keys

- name: Repositories
  ansible.builtin.import_tasks: repositories.yml
  tags:
    - manala_apt
    - manala_apt.repositories

- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - manala_apt
    - manala_apt.packages

- name: Holds
  ansible.builtin.import_tasks: holds.yml
  tags:
    - manala_apt
    - manala_apt.holds

- name: Update
  ansible.builtin.import_tasks: update.yml
  when: __manala_apt['update']
  tags:
    - manala_apt
    - manala_apt.update
    - manala.update
