---

- name: Update > Backup package marks  # noqa risky-shell-pipe no-tabs
  ansible.builtin.shell: >
    dpkg --get-selections {{ item }}
    | cut -f 2-
    | tr -d '\t'
  changed_when: false
  loop: "{{ manala_apt_update_holds }}"
  register: __manala_apt_update_marks_results

- name: Update > Hold packages  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    echo '{{ item.0 }} hold'
    | dpkg --set-selections
  when:
    - item.1
    - item.1 != 'hold'
  loop: |
    {{
      manala_apt_update_holds
        | zip(
          __manala_apt_update_marks_results.results | map(attribute='stdout') | list
        )
        | list
    }}

- name: Update > Upgrade dist
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Update > Restore package marks  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    echo '{{ item.0 }} {{ item.1 }}'
    | dpkg --set-selections
  when: item.1
  loop: |
    {{
      manala_apt_update_holds
        | zip(
          __manala_apt_update_marks_results.results | map(attribute='stdout') | list
        )
        | list
    }}
