---

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  tags:
    - manala_npm
    - manala_npm.requirements

- name: Update
  ansible.builtin.import_tasks: update.yml
  when: __manala_npm['update']
  tags:
    - manala_npm
    - manala_npm.update
    - manala.update

- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - manala_npm
    - manala_npm.packages
