---

- name: Configs - Tmpfiles
  ansible.builtin.import_tasks: tmpfiles_configs.yml
  tags:
    - manala_systemd
    - manala_systemd.tmpfiles_configs

- name: Configs - System
  ansible.builtin.import_tasks: system_configs.yml
  tags:
    - manala_systemd
    - manala_systemd.system_configs

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_systemd
    - manala_systemd.services
    - manala.services
