---

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  tags:
    - manala_ohmyzsh
    - manala_ohmyzsh.requirements

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_ohmyzsh
    - manala_ohmyzsh.install

- name: Custom Themes
  ansible.builtin.import_tasks: custom_themes.yml
  tags:
    - manala_ohmyzsh
    - manala_ohmyzsh.custom_themes

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - manala_ohmyzsh
    - manala_ohmyzsh.users
