---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_cron
    - manala_cron.install

- name: Files
  ansible.builtin.import_tasks: files.yml
  tags:
    - manala_cron
    - manala_cron.files

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_cron
    - manala_cron.services
    - manala.services
