---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_ssh
    - manala_ssh.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_ssh
    - manala_ssh.config

- name: Known Hosts
  ansible.builtin.import_tasks: known_hosts.yml
  tags:
    - manala_ssh
    - manala_ssh.known_hosts

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_ssh
    - manala_ssh.services
    - manala.services
