---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_network
    - manala_network.install

- name: Hosts
  ansible.builtin.import_tasks: hosts.yml
  tags:
    - manala_network
    - manala_network.hosts

- name: Resolver config
  ansible.builtin.import_tasks: resolver_config.yml
  tags:
    - manala_network
    - manala_network.resolver_config

- name: Interfaces config
  ansible.builtin.import_tasks: interfaces_config.yml
  tags:
    - manala_network
    - manala_network.interfaces_config

- name: Interfaces configs
  ansible.builtin.import_tasks: interfaces_configs.yml
  tags:
    - manala_network
    - manala_network.interfaces_configs

- name: Routing Tables
  ansible.builtin.import_tasks: routing_tables.yml
  tags:
    - manala_network
    - manala_network.routing_tables
