---

- name: Routing Tables > File  # noqa no-tabs
  ansible.builtin.lineinfile:
    path: "{{ manala_network_routing_tables_file }}"
    regexp: "^{{ item.key }}\\s+"
    line: "{{ item.key ~ '\t' ~ item.value }}"
  loop: "{{ manala_network_routing_tables | dict2items }}"
