---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_supervisor
    - manala_supervisor.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_supervisor
    - manala_supervisor.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_supervisor
    - manala_supervisor.configs

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_supervisor
    - manala_supervisor.services
    - manala.services
