---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_dhcp
    - manala_dhcp.install

- name: Interfaces
  ansible.builtin.import_tasks: interfaces.yml
  tags:
    - manala_dhcp
    - manala_dhcp.interfaces

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_dhcp
    - manala_dhcp.config

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_dhcp
    - manala_dhcp.services
    - manala.services
