---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_mysql
    - manala_mysql.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_mysql
    - manala_mysql.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_mysql
    - manala_mysql.configs

- name: Data
  ansible.builtin.import_tasks: data.yml
  tags:
    - manala_mysql
    - manala_mysql.data

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_mysql
    - manala_mysql.services
    - manala.services

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - manala_mysql
    - manala_mysql.users

- name: Databases
  ansible.builtin.import_tasks: databases.yml
  tags:
    - manala_mysql
    - manala_mysql.databases

- name: Replications
  ansible.builtin.import_tasks: replications.yml
  tags:
    - manala_mysql
    - manala_mysql.replications
