---

- name: Restart nginx
  ansible.builtin.command: nginx -t
  changed_when: true
  notify:
    - Do restart nginx
  # Deprecated
  listen: nginx restart

- name: Do restart nginx
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nginx
  # Deprecated
  listen: do nginx restart
