---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_proftpd
    - manala_proftpd.install

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_proftpd
    - manala_proftpd.configs

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - manala_proftpd
    - manala_proftpd.users

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_proftpd
    - manala_proftpd.services
    - manala.services
