---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_glusterfs
    - manala_glusterfs.install

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_glusterfs
    - manala_glusterfs.services

- name: Volumes
  ansible.builtin.import_tasks: volumes.yml
  tags:
    - manala_glusterfs
    - manala_glusterfs.volumes
