---

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  tags:
    - manala_pam_ssh_agent_auth
    - manala_pam_ssh_agent_auth.requirements

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_pam_ssh_agent_auth
    - manala_pam_ssh_agent_auth.install

- name: Sudo
  ansible.builtin.import_tasks: sudo.yml
  tags:
    - manala_pam_ssh_agent_auth
    - manala_pam_ssh_agent_auth.sudo
