---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_git
    - manala_git.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_git
    - manala_git.config

- name: Repositories
  ansible.builtin.import_tasks: repositories.yml
  tags:
    - manala_git
    - manala_git.repositories
