---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_maxscale
    - manala_maxscale.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_maxscale
    - manala_maxscale.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_maxscale
    - manala_maxscale.configs

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - manala_maxscale
    - manala_maxscale.users

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_maxscale
    - manala_maxscale.services
