---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_keepalived
    - manala_keepalived.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_keepalived
    - manala_keepalived.config

- name: Environment
  ansible.builtin.import_tasks: environment.yml
  tags:
    - manala_keepalived
    - manala_keepalived.environment

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_keepalived
    - manala_keepalived.services
    - manala.services
