---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_ansible
    - manala_ansible.install

- name: Hosts
  ansible.builtin.import_tasks: hosts.yml
  tags:
    - manala_ansible
    - manala_ansible.hosts

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_ansible
    - manala_ansible.config

- name: Host vars
  ansible.builtin.import_tasks: host_vars.yml
  tags:
    - manala_ansible
    - manala_ansible.hosts_vars

- name: Group vars
  ansible.builtin.import_tasks: group_vars.yml
  tags:
    - manala_ansible
    - manala_ansible.group_vars
