---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_sudo
    - manala_sudo.install

- name: Sudoers
  ansible.builtin.import_tasks: sudoers.yml
  tags:
    - manala_sudo
    - manala_sudo.sudoers
