---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_fail2ban
    - manala_fail2ban.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_fail2ban
    - manala_fail2ban.config

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_fail2ban
    - manala_fail2ban.services
    - manala.services
