---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_elasticsearch
    - manala_elasticsearch.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_elasticsearch
    - manala_elasticsearch.config

- name: Environment
  ansible.builtin.import_tasks: environment.yml
  tags:
    - manala_elasticsearch
    - manala_elasticsearch.environment

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_elasticsearch
    - manala_elasticsearch.services
    - manala.services

- name: Plugins
  ansible.builtin.import_tasks: plugins.yml
  tags:
    - manala_elasticsearch
    - manala_elasticsearch.plugins
