---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_dnsmasq
    - manala_dnsmasq.install

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_dnsmasq
    - manala_dnsmasq.configs

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_dnsmasq
    - manala_dnsmasq.services
    - manala.services
