---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts: debian
  tasks:
    - block:  # noqa name[missing]
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.dhcp
          vars:
            manala_dhcp_interfaces:
              - "{{ ansible_default_ipv4.interface }}"
            manala_dhcp_config_content: |
              subnet {{ ansible_default_ipv4.network }} netmask {{ ansible_default_ipv4.netmask }} {
              }
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('ansible.builtin.template', 'goss/default.yml.j2') }}"
          changed_when: false
