---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_docker
    - manala_docker.install

- name: Config - Daemon
  ansible.builtin.import_tasks: config_daemon.yml
  tags:
    - manala_docker
    - manala_docker.config_daemon

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_docker
    - manala_docker.services
    - manala.services

- name: Applications
  ansible.builtin.import_tasks: applications.yml
  tags:
    - manala_docker
    - manala_docker.applications

- name: Containers
  ansible.builtin.import_tasks: containers.yml
  tags:
    - manala_docker
    - manala_docker.containers

- name: Update
  ansible.builtin.import_tasks: update.yml
  when: __manala_docker['update']
  tags:
    - manala_docker
    - manala_docker.update
    - manala.update
