---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_bind
    - manala_bind.install

- name: Options
  ansible.builtin.import_tasks: options.yml
  tags:
    - manala_bind
    - manala_bind.options

- name: Logs
  ansible.builtin.import_tasks: logs.yml
  tags:
    - manala_bind
    - manala_bind.logs

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_bind
    - manala_bind.configs

- name: Zones
  ansible.builtin.import_tasks: zones.yml
  tags:
    - manala_bind
    - manala_bind.zones

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_bind
    - manala_bind.services
    - manala.services

- name: Zones - Records
  ansible.builtin.import_tasks: zones_records.yml
  tags:
    - manala_bind
    - manala_bind.zones_records
