---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_telegraf
    - manala_telegraf.install

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - manala_telegraf
    - manala_telegraf.config

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_telegraf
    - manala_telegraf.configs

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - manala_telegraf
    - manala_telegraf.services
    - manala.services
