name: Molecule - Zsh

on:
  pull_request:
    paths:
      - .manala.yaml
      - .github/workflows/molecule.zsh.yml
      - .config/molecule/config.yml
      - molecule/Dockerfile.*
      - molecule/zsh/**
      - roles/zsh/**
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Run with tmate debugging
        required: false
        default: false

jobs:
  zsh:
    uses: ./.github/workflows/molecule.yaml
    with:
      debug: ${{ inputs.debug == true }}
      scenario: zsh
