name: Molecule - Dhcp

on:
  pull_request:
    paths:
      - .manala.yaml
      - .github/workflows/molecule.dhcp.yml
      - .config/molecule/config.yml
      - molecule/Dockerfile.*
      - molecule/dhcp/**
      - roles/dhcp/**
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Run with tmate debugging
        required: false
        default: false

jobs:
  dhcp:
    uses: ./.github/workflows/molecule.yaml
    with:
      debug: ${{ inputs.debug == true }}
      scenario: dhcp
